networks:
  meoworld:
    external: true

volumes:
  meoworld-logs:
    external: true

services:
  message-broker:
    image: redis:latest
    hostname: meoworld-message-broker
    restart: on-failure:3
    networks:
      - meoworld

  gateway:
    build:
      context: ./
      dockerfile: GatewayDockerfile
    ports:
      - "8080:8080"
    environment:
      - MESSAGE_BROKER_ADDRESS=meoworld-message-broker
      - CACHE_SERVERS=cache-storage-01;cache-storage-02
    depends_on:
      - message-broker
    restart: on-failure:3
    volumes:
      - meoworld-logs:/usr/src/app/logs/
    networks:
    - meoworld

  posts-service:
    build:
      context: ./
      dockerfile: ./services/posts/Dockerfile
    environment:
      - MESSAGE_BROKER_ADDRESS=meoworld-message-broker
      - DATABASE_ADDRESS=posts-database
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - message-broker
      - gateway
    restart: on-failure:3
    volumes:
      - meoworld-logs:/usr/src/app/logs/
    networks:
    - meoworld

  comments-service:
    build:
      context: ./
      dockerfile: ./services/comments/Dockerfile
    environment:
      - MESSAGE_BROKER_ADDRESS=meoworld-message-broker
      - DATABASE_ADDRESS=mysql-router
      - DATABASE_PORT=6446 # read-write port
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - message-broker
      - gateway
    restart: on-failure:3
    volumes:
      - meoworld-logs:/usr/src/app/logs/
    networks:
    - meoworld

  cache-storage-01:
    image: redis:latest
    hostname: cache-storage-01
    restart: on-failure:3
    networks:
    - meoworld

  cache-storage-02:
    image: redis:latest
    hostname: cache-storage-02
    restart: on-failure:3
    networks:
    - meoworld
