volumes:
  posts-db:
    external: true
  comments-db:
    external: true
  meoworld-logs:
    external: true

services:
  message-broker:
    image: redis:latest
    hostname: meoworld-message-broker
    restart: on-failure:3

  gateway:
    build:
      context: ./
      dockerfile: GatewayDockerfile
    ports:
      - "8080:8080"
    environment:
      - MESSAGE_BROKER_ADDRESS=meoworld-message-broker
      - CACHE_SERVERS=cache-storage-01;cache-storage-02
    depends_on:
      - message-broker
    restart: on-failure:3
    volumes:
      - meoworld-logs:/usr/src/app/logs/

  posts-service:
    build:
      context: ./
      dockerfile: ./services/posts/Dockerfile
    environment:
      - MESSAGE_BROKER_ADDRESS=meoworld-message-broker
      - DATABASE_ADDRESS=posts-database
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - message-broker
      - gateway
    restart: on-failure:3
    volumes:
      - meoworld-logs:/usr/src/app/logs/

  comments-service:
    build:
      context: ./
      dockerfile: ./services/comments/Dockerfile
    environment:
      - MESSAGE_BROKER_ADDRESS=meoworld-message-broker
      - DATABASE_ADDRESS=comments-database
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - message-broker
      - gateway
    restart: on-failure:3
    volumes:
      - meoworld-logs:/usr/src/app/logs/

  posts-database:
    image: mysql:latest
    hostname: posts-database
    volumes:
      - posts-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
    restart: on-failure:3

  comments-database:
    image: mysql:latest
    hostname: comments-database
    volumes:
      - comments-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
    restart: on-failure:3

  cache-storage-01:
    image: redis:latest
    hostname: cache-storage-01
    restart: on-failure:3

  cache-storage-02:
    image: redis:latest
    hostname: cache-storage-02
    restart: on-failure:3
